### ISSUE TITLE
What Do I Do With This Fork?

### ISSUE THREAD

**Issue by jimorc** [kostecky/SDRPlusPlus#1]
I am not sure at this point what I should do. Do I clone this repository and build it on my M1 Mac? If so, that just gives me the same problems that I have with Alexandre Rouma's repository when I try to build it. That is, the call to cmake complains that it cannot find glfw.

Is there an executable? Is that what SDR++.app/MacOS/sdrpp is? I downloaded it and when I tried to execute, all I get is:

_œ˙Ì˛������������à��Ö� ��������H���__PAGEZERO��������������������������������������������������������8��__TEXT������������������@���������������@�������������������__text����������__TEXT����������®?������������®?���������������Ä������������__stubs���������__TEXT����������¨?������������¨?��������������Ä�����������__unwind_info���__TEXT����������∏?�����H�������∏?��������������������������������ò���__DATA_CONST�����@������@�������@�������@������������������__got�����������__DATA_CONST�����@�������������@������������������������������H���__LINKEDIT�������Ä������Ä�������Ä������êI��������������������4��Ä����Ä��p���3��Ä���pÄ��0���������®Ä�����‡Ä��0������P������������������������������������������������ÿÄ������������������������ ������/usr/lib/dyld�������������:3jÀe0Ç±’øXZ™lë2��� �������������������˙*��������������(��Ä���®?�����������������8�����������������@rpath/libsdrpp_core.dylib���������0��������������@rpath/libglfw.3.dylib�����X���������������/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL������8����������

���
�@rpath/libfftw3f.3.dylib�����������8�������������@rpath/libvolk.2.5.dylib�����������0�������������@rpath/libzstd.1.dylib�����0�������������/usr/lib/libc++.1.dylib����8���������d���/usr/lib/libSystem.B.dylib������&������†Ä�����)������®Ä������������Å��ÄH����Ä(������@loader_path/../Frameworks�����������������������������������

and so forth.

I apologize for having to ask this, but I am very new to Macs, and have never attempted any software builds, etc until today.

**Comment by kostecky** [comment]
If you have an m1 mac, just move the `SDR++.app` folder to /Applications/ and click on it in the GUI. It should "just work"

**Comment by jimorc** [comment]
Thanks. That info pointed me in the right direction. I cloned your repository. Under SDRPlusPlus, there is an app called SDR++. I copied that to the Applications folder and now it works.

May I suggest that this be added to the README or somewhere else that is obvious. I realize that the current README is a direct copy of the original, but this info should be placed somewhere so others don't have to ask.

**Comment by kostecky** [comment]
I've added a header to the README.md. Thanks!
